## 1.HTML гэж юу вэ?

Вэб хуудсыг HTML хэлний тусламжтай хийдэг. HTML хэл нь script хэл бөгөөд ямар нэг хөрвүүлэлт шаарддаггүй, дурын текст боловсруулах програм дээр бичиж болдог. Харин тухайн файлаа *.html юмуу *.htm форматтай хадгалах хэрэгтэй. Дараа нь уг файлаа Вэб браузер програм дээр нээж ажиллуулах хэрэгтэй.
HTML хэлний командуудыг TAG гэж нэрлэх ба TAG нь эхлэл ба төгсгөлөөс тогтоно. Эхлэл нь <…> хашилтан дотор, төгсгөл нь хашилтан дотор тус тус байрладаг. Гүйцэтгэх үйлдлээ эхлэл ба төгсгөлийн хооронд бичнэ. Жишээлбэл, хуудсанд гарчиг оруулахын тулд TITLE тагийг ашиглах бөгөөд дараах байдлаар бичнэ.
HTML тагуудыг хэдэн хэдэн ангилалд оруулан авч үзэж болно. Үүнд:
1. Html Basics–Вэб хуудасны үндсэн тагууд,
2. Html Text–Текстэн мэдээлэлтэй ажиллах тагууд,
3. Html Lists–Жагсаалт үүсгэх тагууд,
4. Html Images–Зурагтай ажиллах тагууд,
5. Html Links–Холбоос тагууд,
6. Html Backgrounds–Вэб хуудасны дэвсгэрийг тохируулах тагууд,
7. Html Tables–Хүснэгттэй ажиллах тагууд,
8. Html Frames–Frame-тэй ажиллах тагууд,
9. Html Forms–Form, анкеттай ажиллах тагууд,
10. Html Metatags–Хайлтын систем болон браузертай ажиллах тагууд,
11. Html Hexcolors-Өнгөтэй холбоотой тагууд.

Үндсэн HTML хэлний бүтэц нь толгойн хэсэг ба их биеийн хэсгээс тогтох ба HTML, HEAD, BODY гэсэн үндсэн 3 тагийг агуулах бөгөөд дараах хэлбэртэй байна. Үүнд:



. . .
. . . Толгойн хэсэг
. . .

. . .
. . . Их биеийн хэсэг
. . .




Энд:
- … таг нь Вэб хуудасны эхлэл, төгсгөлийг,
- … таг нь толгойн хэсэг буюу Вэб хуудасны гарчиг гэх мэт элементүүдийг,
- … таг нь их биеийн хэсэг буюу HTML хэл дээр бичигдэж байгаа ихэнх эх кодыг агуулна.
Тухайн тохиолдолд Вэб хуудсанд ашиглагдсан Javascript, ActiveX Script гэх мэт бусад Script хэлний код HEAD таг дотор тодорхойлогдож болно.
HTML тагууд нь мөн параметр (option)-ууд агуулж болох ба энэ нь хуудсыг нэмэлт боломжуудаар хангаж өгдөг.

#### Хэрэгцээт TAG уудыг дараах site аас харна уу.
#### https://www.w3schools.com/tags/ref_byfunc.asp

# 2.WEB crawling/scraping
Вэб сайтаас өгөгдлийг автомат аргаар цуглуулахыг вэб скрапинг гэнэ. Зарим вэб сайтууд хэрэглэгчдэд өөрийн мэдээллийг автомат хэрэгслээр скрап хийхийг хориглодог. Вэб сайтууд үүнийг хоёр шалтгаанаар хийж болно:

Сайтад мэдээллээ хамгаалах үндэслэлтэй шаардлага байгаа. 
Жишээлбэл, Google Maps нь хэт олон үр дүнг хурдан хугацаанд скрап хийхийг зөвшөөрдөггүй.

Сайт руу давтан олон хүсэлт илгээх нь хэрэглэгчдэд зориулсан вэб сайтыг удаашруулж, серверийг ачааллуулж, вэб сайт бүрэн ажиллахаа болиход хүргэж болзошгүй.

Python чадвараа вэб скрапинг хийхэд ашиглахаасаа өмнө зорилтот вэб сайтынхаа ашиглалтын бодлогыг(use policy) шалгаж, автомат хэрэгсэл ашиглан вэб сайт руу нэвтрэх нь түүний нөхцөлийг зөрчиж байгаа эсэхийг шалгах хэрэгтэй. Хууль эрхзүйн хувьд вэб скрап хийх нь нэлээд маргаантай асуудал юм.

### 2.1 BeautifulSoup

Beautiful Soup нь вэб хуудаснаас мэдээлэл цуглуулахыг хялбар болгодог сан юм. Энэ нь HTML эсвэл XML парсер дээр суурилсан бөгөөд хайх, өөрчлөхөд зориулсан Python сан юм.
https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [ ]:
!pip3 install beautifulsoup4

In [ ]:
!pip3 install lxml

In [1]:
html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""

In [4]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc, 'html.parser')

print(soup.prettify())

<html>
 <head>
  <title>
   The Dormouse's story
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The Dormouse's story
   </b>
  </p>
  <p class="story">
   Once upon a time there were three little sisters; and their names were
   <a class="sister" href="http://example.com/elsie" id="link1">
    Elsie
   </a>
   ,
   <a class="sister" href="http://example.com/lacie" id="link2">
    Lacie
   </a>
   and
   <a class="sister" href="http://example.com/tillie" id="link3">
    Tillie
   </a>
   ;
and they lived at the bottom of a well.
  </p>
  <p class="story">
   ...
  </p>
 </body>
</html>

### element haih

In [5]:
#tag aar haih
soup.title

In [ ]:
# find method oor haih

In [1]:
soup.find("title")

NameError: name 'soup' is not defined

In [11]:
#find method n hamgiin ehnii element iig awdag. find_all gewel buh element iig awna
soup.find("a")

In [8]:
# attribution name eer haih
soup.find(id="link1")

In [10]:
soup.find(class_="sister")

In [12]:
soup.find_all("a")

[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>]

In [13]:
soup.find_all("p")

[<p class="title"><b>The Dormouse's story</b></p>,
 <p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [17]:
soup.find_all("p", class_="title")

### Text scraping

In [18]:
soup.text

"The Dormouse's story\n\nThe Dormouse's story\nOnce upon a time there were three little sisters; and their names were\nElsie,\nLacie and\nTillie;\nand they lived at the bottom of a well.\n...\n"

In [19]:
title = soup.find("title")
title.text

"The Dormouse's story"

In [23]:
ps = soup.find_all("a")
ps

[<a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a>,
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>]

In [27]:
for p in ps:
    print(p.text)

Elsie
Lacie
Tillie

In [28]:
ps[1].text

'Lacie'

In [30]:
ps = soup.find_all(class_="story")
ps

[<p class="story">Once upon a time there were three little sisters; and their names were
 <a class="sister" href="http://example.com/elsie" id="link1">Elsie</a>,
 <a class="sister" href="http://example.com/lacie" id="link2">Lacie</a> and
 <a class="sister" href="http://example.com/tillie" id="link3">Tillie</a>;
 and they lived at the bottom of a well.</p>,
 <p class="story">...</p>]

In [31]:
for p in ps:
    print(p.text)

Once upon a time there were three little sisters; and their names were
Elsie,
Lacie and
Tillie;
and they lived at the bottom of a well.
...

### Link scraping

In [35]:
new_soup = soup.find("a")
new_soup

In [36]:
new_soup["href"]

'http://example.com/elsie'

In [37]:
ps = soup.find_all("a")
for p in ps:
    print(p["href"])

http://example.com/elsie
http://example.com/lacie
http://example.com/tillie

# Image scraping

In [48]:
html_doc = """<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>
<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;and they lived at the bottom of a well.</p>
<p class="story">...</p>
<img src="https://static.wikia.nocookie.net/looking-glass/images/1/15/Aliceposter.png" alt="A beautiful image" width="300" height="420">
<table border="1"><tr><th>Name</th><th>Age</th><th>Location</th></tr><tr>
<td>Elsie</td><td>10</td><td>Well</td></tr><tr>
<td>Lacie</td><td>8</td><td>Well</td></tr><tr>
<td>Tillie</td><td>9</td><td>Well</td></tr>
</table>
</body></html>
"""

In [49]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc, 'html.parser')

print(soup.prettify())

<html>
 <head>
  <title>
   The Dormouse's story
  </title>
 </head>
 <body>
  <p class="title">
   <b>
    The Dormouse's story
   </b>
  </p>
  <p class="story">
   Once upon a time there were three little sisters; and their names were
   <a class="sister" href="http://example.com/elsie" id="link1">
    Elsie
   </a>
   ,
   <a class="sister" href="http://example.com/lacie" id="link2">
    Lacie
   </a>
   and
   <a class="sister" href="http://example.com/tillie" id="link3">
    Tillie
   </a>
   ;and they lived at the bottom of a well.
  </p>
  <p class="story">
   ...
  </p>
  <img alt="A beautiful image" height="420" src="https://static.wikia.nocookie.net/looking-glass/images/1/15/Aliceposter.png" width="300"/>
  <table border="1">
   <tr>
    <th>
     Name
    </th>
    <th>
     Age
    </th>
    <th>
     Location
    </th>
   </tr>
   <tr>
    <td>
     Elsie
    </td>
    <td>
     10
    </td>
    <td>
     Well
    </td>
   </tr>
   <tr>
    <td>
     Lacie
    </td>
    <td>
     8
    </td>
    <td>
     Well
    </td>
   </tr>
   <tr>
    <td>
     Tillie
    </td>
    <td>
     9
    </td>
    <td>
     Well
    </td>
   </tr>
  </table>
 </body>
</html>

In [41]:
image = soup.find("img")
image

In [50]:
image = soup.find_all("img")[0]
image

In [51]:
image_source = image["src"]
image_source

'https://static.wikia.nocookie.net/looking-glass/images/1/15/Aliceposter.png'

# Table scraping

In [52]:
table = soup.find("table")
table

<table border="1"><tr><th>Name</th><th>Age</th><th>Location</th></tr><tr>
<td>Elsie</td><td>10</td><td>Well</td></tr><tr>
<td>Lacie</td><td>8</td><td>Well</td></tr><tr>
<td>Tillie</td><td>9</td><td>Well</td></tr>
</table>

In [54]:
columns = table.find("tr").find_all("th")
columns
columns_text = []
for col in columns:
    columns_text.append(col.text)
columns_text

['Name', 'Age', 'Location']

In [60]:
table_rows = table.find_all("tr")[1:]
table_dictionary = []
for table_row in table_rows:
    row_dictionary = {}
    row_dictionary[columns_text[0]] = table_row.find_all("td")[0].text
    row_dictionary[columns_text[1]] = table_row.find_all("td")[1].text
    row_dictionary[columns_text[2]] = table_row.find_all("td")[2].text
    table_dictionary.append(row_dictionary)
table_dictionary

[{'Name': 'Elsie', 'Age': '10', 'Location': 'Well'},
 {'Name': 'Lacie', 'Age': '8', 'Location': 'Well'},
 {'Name': 'Tillie', 'Age': '9', 'Location': 'Well'}]

In [61]:
import pandas as pd

table_df = pd.DataFrame.from_dict(table_dictionary)
table_df

     Name Age Location
0   Elsie  10     Well
1   Lacie   8     Well
2  Tillie   9     Well

# Request

In [9]:
import requests
from bs4 import BeautifulSoup

url = "https://www.barilga.mn/a/"
reqs = requests.get(url)
soup = BeautifulSoup(reqs.content, 'html.parser')

ModuleNotFoundError: No module named 'requests'

In [10]:
name = soup.find("a", class_="advert__content-title").text.strip()
name

NameError: name 'soup' is not defined

In [71]:
names = soup.find_all("a", class_="advert__content-price _not-title")

for name in names:
    print(name.text.strip())

120 сая ₮
750 сая ₮
225 сая ₮
450 сая ₮ 480 сая ₮
158 сая ₮
330 сая ₮
9.5 сая ₮
39 сая ₮
741.15 сая ₮
2.75 сая ₮
1.38 Тэрбум ₮
176 сая ₮
700 сая ₮
125 сая ₮
8 сая ₮
195 сая ₮
5.2 сая ₮
10 сая ₮
615 сая ₮
228 сая ₮
115 сая ₮
420 сая ₮
1.04 Тэрбум ₮
690 сая ₮
800 сая ₮
560 сая ₮
410 сая ₮ 460 сая ₮
245 сая ₮
1.5 Тэрбум ₮
129 сая ₮
500 сая ₮
110.5 сая ₮
114 сая ₮
210 сая ₮
146 сая ₮
700 сая ₮
3.2 сая ₮
559.44 сая ₮
180 сая ₮
165 сая ₮
120 сая ₮
1.08 Тэрбум ₮
1.1 Тэрбум ₮
105 сая ₮
4.5 сая ₮
115 сая ₮ 150 сая ₮
368 сая ₮
1.6 Тэрбум ₮
320 сая ₮ 343 сая ₮
35 сая ₮
499 сая ₮
28 сая ₮
250 сая ₮
900 сая ₮
770 сая ₮
180 сая ₮
167 сая ₮
175 сая ₮
102 сая ₮
13 сая ₮

In [81]:
links = soup.find_all("div", class_="swiper-wrapper")
for link in links:
    print(link.find("a")["href"])

/adv/9298845_bzd-monel/
/adv/9253952_tokyo-town-3-oroo-khudaldana/
/adv/9291714_suis-ard/
/adv/9295668_nogoon-urlan-khotgon/
/adv/9263649_ofitsert-3-oroo-55m2-khiamd/
/adv/9298413_amankhuur-khotkhond-super-zasvar-khiisen-4-oroo-bair-zarna/
/adv/9286509_khud-river-garden-ard-siti-terras-mult-khaus-d-198mkv-5-oroo-oron-suuts/
/adv/9298289_khashaa-baishin-zarna/
/adv/9298214_khud-15-r-khoroo-vega-city-khotkhond-91-5-mkv-tsoo-shine-4-oroo-khudaldana/
/adv/9298051_arvai-villa-91-69mkv-mastertai-3-oroo/
/adv/8678186_3-4-r-khoroololyn-modny-2-t-shineer-ashiglaltand-orson-offis-khudaldana/
/adv/8993926_118-surguuliin-khazhuud-shine-2-oroo-bair/
/adv/9227354_royal-green-villa-4-oroo-2-garazhyn-khamt/
/adv/9297667_shine-orgoo-khoroolold/
/adv/9296800_khud-15-r-khoroo-tsengeldekh-1-khotkhond-69-93mkv-3-oroo-bair-zarna/
/adv/9235205_baianbulagt-zuslangiin-baishin-zarna/
/adv/9297507_king-tower-5-eelzh-3-oroo/
/adv/9288234_yaraltai-8-ail-gazar-zarna/
/adv/9297251_bzd-26khoroo-emerald-residence-d-5-oroo-oron-suuts-khudaldana/
/adv/9267461_songinr-khairkhan-duureg-32-t-zam-daguu-khudaldaa-uilchilgeenii-talbai-zarna/
/adv/9294948_new-garden/
/adv/9297028_darkhand-lkham-market-8-n-neriin-169m2-delguur-une-tokhirzh-zarna/
/adv/9297038_khud-15-r-khoroo-royal-garden-khotkhond-207mkv-6-oroo-oron-suuts-khudaldana/
/adv/9284186_luxhouse-2/
/adv/9296562_khunnu-1-r-eelzhind-4-oroo-khudaldana/
/adv/9296927_global-town-khotkhon-shine-3-oroo/
/adv/9274515_bzd-36-khoroo-emerald-rezidens-khotkhond-3-oroo-bair-zarna-grashyn-khamt-99054366/
/adv/9210247_6-bichil-khoroolold-4-oroo-bair-zarna/
/adv/7587760_gazar/
/adv/9289496_ofitser-taund-1-oroo-khudaldana/
/adv/9296689_khulemzhiin-azh-akhui-une-tokhirch-zarna/
/adv/9296612_zhukov-buiand-od-khotkhond-1-oroo-khudaldana/
/adv/9283005_moneld-108-r-bairand-1-oroo-oron-suuts-khudaldana/
/adv/9296396_1-r-khoroolold-khashaa-baisan-zarna/
/adv/9247697_shine-khotkhon-khoroolold-3-oroo-bair-zarna/
/adv/9191523_khud-zaisan-khaais-uragshaa-nomun-villazh-khotkhond-112-8mkv-uilchilgeenii-talbai/
/adv/9296080_asahi-residence-khotkhon-2-oroo-bair/
/adv/9195919_tsengeldekh-khotkhond-70mkv-3-oroo/
/adv/9087664_1400m2-gazartai-4-tal-tomor-khashaatai-144-m2-2-davkhar-dunzen-khaus-khudaldana/
/adv/9276378_ofitsert/
/adv/9295905_azh-akhuin-aguulakh-uildver-khiikh-gazar-oron-suuts-barzh-bolno/
/adv/9295777_river-garden-1-khotkhond-4-oroo-bair-zarna/
/adv/9295654_wellington-town/
/adv/9295559_khilchin-khotkhon-7davkhar-bairny-5-davkhart-2oroo-bair-galtogoo-tusdaa/
/adv/9272177_elizabeth-khotkhond-105-48mkv-3oroo-bair-zarna/
/adv/9098433_zam-daguu-nuurnii-egneenii-khashaa-baishin-khudaldana/
/adv/9162454_tsever-agaartai-buren-tsutgamal-zalaatyn-aman-dakh-3-oroo-shine-bair/
/adv/9202922_22-n-shine-avto-zakh-ruu-iavakh-zam-daguu-1r-egneend/
/adv/9242451_iaarmag-nukhtiin-am-sunset-town-house-3-oroo-bair-iaaraltai-khudaldana/
/adv/9294973_narny-khoroolold-6r-bairny-door-zogsool-zarna/
/adv/9294725_uschin-goo-saikhny-belen-biznes/
/adv/9294554_ar-gunted-zuslangiin-khashaa-gazar/
/adv/9294532_goodoin-zusland-mash-goio-bairlald-110m2-talbaitai-4-oroo-khaus-zarna/
/adv/9277042_kuveitiin-amand-khaus-zarna/
/adv/9294414_khud-18r-khoroo-khunnu-2222-3r-eelzhind-96-mkv-offis-chigleleer-tokhizhuulsan-4-oroo/
/adv/9290191_khan-uul-19khoroo-dol-khotkhond-2-oroo/
/adv/9294351_2-oroo-oron-suuts/
/adv/9294099_khud-15-khoroo-rapid-kharsh-khotkhond-1-oroo-khudaldana/
/adv/9293954_baianzurkh-khoroolold-uragshaa-kharsan-tsonkhtoi-buren-tavilgatai-1-oroo-bair-zarna/
/adv/9261281_ss-garden-d-4-oroo-bair-oron-suuts-khudaldana/

In [88]:
names = soup.find_all("a", class_="advert__content-title")
names_list = []
for name in names:
    if name.text.strip() == None:
        names_list.append("")
    else:
        names_list.append(name.text.strip())
names_list[:5]

['Бзд монел хашаа байшин',
 'Tokyo town 3 өрөө 101.32м2 байр',
 'Суис-ийн ард 2 өрөө 47.6мк байр',
 'Сбд ногоон урлан хотхонд 3 өрөө 83мкв',
 'Офицерт 3 өрөө 55м2 байр']

In [89]:
prices = soup.find_all("a", class_="advert__content-price _not-title")
prices_list = []
for price in prices:
    if price.text.strip() == None:
        prices_list.append("")
    else:
        prices_list.append(price.text.strip())
prices_list[:5]

['120 сая ₮', '750 сая ₮', '225 сая ₮', '450 сая ₮ 480 сая ₮', '158 сая ₮']

In [90]:
df = pd.DataFrame()
df["name"] = names_list
df["price"] = prices_list
df.to_excel("/Users/ddam-m0101/Downloads/sample_unegui.xlsx", index = False)

In [93]:
import requests
from bs4 import BeautifulSoup
import time

home_url = "https://www.unegui.mn/l-hdlh/l-hdlh-zarna/"
names_list = []
for i in range(1,11):
    print(i)
    page_url = home_url + "?page=" + str(i)
    reqs = requests.get(page_url)
    soup = BeautifulSoup(reqs.content, 'html.parser')
    time.sleep(3)
    
    names = soup.find_all("a", class_="advert__content-title")
    for name in names:
        if name.text.strip() == None:
            names_list.append("")
        else:
            names_list.append(name.text.strip())

1
2
3
4
5
6
7
8
9
10

In [95]:
len(names_list)

600

In [96]:
import requests
from bs4 import BeautifulSoup
import time

home_url = "https://www.unegui.mn/l-hdlh/l-hdlh-zarna/"
names_list = []
for i in range(1,6):
    print(i)
    page_url = home_url + "?page=" + str(i)
    reqs = requests.get(page_url)
    soup = BeautifulSoup(reqs.content, 'html.parser')
    time.sleep(3)
    
    names = soup.find_all("a", class_="advert__content-title")
    for name in names:
        if name.text.strip() == None:
            names_list.append("")
        else:
            names_list.append(name.text.strip())

1
2
3
4
5

In [4]:
import requests
from bs4 import BeautifulSoup

url = "https://www.unegui.mn/l-hdlh/"
reqs = requests.get(url)
soup = BeautifulSoup(reqs.content, 'html.parser')

ModuleNotFoundError: No module named 'requests'

In [99]:
prices = soup.find_all("a", class_="advert__content-price _not-title")
prices_list = []
for price in prices:
    if price.text.strip() == None:
        prices_list.append("")
    else:
        prices_list.append(price.text.strip())
print(len(prices_list))
prices_list[:5]

60

['300 сая ₮', '146 сая ₮', '159 сая ₮', '228 сая ₮', '400 сая ₮']

In [100]:
whens = soup.find_all("div", class_="advert__content-date")
whens_list = []
for when in whens:
    if when.text.strip() == None:
        whens_list.append("")
    else:
        whens_list.append(when.text.strip())
print(len(whens_list))
whens_list[:5]

60

['6 минутын өмнө',
 '9 минутын өмнө',
 '16 минутын өмнө',
 '31 минутын өмнө',
 '32 минутын өмнө']

In [101]:
wheres = soup.find_all("div", class_="advert__content-place")
where_list = []
for where in wheres:
    if where.text.strip() == None:
        where_list.append("")
    else:
        where_list.append(where.text.strip())
print(len(where_list))
where_list[:5]

60

['УБ — Сонгинохайрхан, Найрамдал',
 'УБ — Баянгол, 10-р хороолол',
 'УБ — Чингэлтэй, Баянбүрдийн тойрог',
 'УБ — Хан-Уул, 120 мянгат',
 'УБ — Сүхбаатар, Сүхбаатар, Хороо 13']

In [109]:
urls = soup.find_all("a", class_="mask")
url_list = []
for url in urls:
    if url["href"] == None:
        url_list.append("")
    else:
        url_list.append(url["href"])
print(len(url_list))
url_list[:5]

60

['/adv/9299060_temuulel-khotkhon-nairamdal-iavakh-zamd-khaus-khudaldana/',
 '/adv/9276761_10-khoroolold-erdmiin-orgoo-surguul-114-r-tsetserlegiin-khazhuud-2-oroo-bair-zarna/',
 '/adv/9299026_oron-suuts-zarna/',
 '/adv/9165500_selkh-zuslan-khiamd-zarn/',
 '/adv/9298985_sbd-13-khoroo-khailaastyn-uuzvaraas-dar-ekh-orokh-4-egnee-zasmal-zam-daguu/']

In [2]:
import requests
from bs4 import BeautifulSoup
import time

home_url = "https://www.unegui.mn/l-hdlh/l-hdlh-zarna/"
names_list = []
prices_list = []
url_list = []
whens_list = []
where_list = []
for i in range(1,6):
    print(i)
    page_url = home_url + "?page=" + str(i)
    reqs = requests.get(page_url)
    soup = BeautifulSoup(reqs.content, 'html.parser')
    time.sleep(3)

    urls = soup.find_all("a", class_="mask")
    for url in urls:
        if url["href"] == None:
            url_list.append("")
        else:
            url_list.append(home_url[:-1]+url["href"])
    
    names = soup.find_all("a", class_="advert__content-title")
    for name in names:
        if name.text.strip() == None:
            names_list.append("")
        else:
            names_list.append(name.text.strip())

    prices = soup.find_all("a", class_="advert__content-price _not-title")
    for price in prices:
        if price.text.strip() == None:
            prices_list.append("")
        else:
            prices_list.append(price.text.strip())

    whens = soup.find_all("div", class_="advert__content-date")
    for when in whens:
        if when.text.strip() == None:
            whens_list.append("")
        else:
            whens_list.append(when.text.strip())

    wheres = soup.find_all("div", class_="advert__content-place")
    for where in wheres:
        if where.text.strip() == None:
            where_list.append("")
        else:
            where_list.append(where.text.strip())

ModuleNotFoundError: No module named 'requests'

In [118]:
df = pd.DataFrame()
df["url"] = url_list
df["name"] = names_list
df["price"] = prices_list
df["hezee"] = where_list
df["haana"] = whens_list
df.to_excel("/Users/ddam-m0101/Downloads/sample_unegui_2.xlsx", index = False)

In [119]:
import pandas as pd

In [124]:
data = pd.read_excel("/Users/ddam-m0101/Downloads/sample_unegui_2.xlsx")
data.head()

,url,name,price,haana,hezee
0,https://www.unegui.mn/adv/9266085_sansart-ktms...,Сансарт ктмс-ийн хойно сүлд хотхонд 79.42 мкв ...,278 сая ₮,"УБ — Баянзүрх, КТМС",Өнөөдөр
1,https://www.unegui.mn/adv/9304290_sky-garden-k...,Sky garden хотхонд 7өрөө,4.36 Тэрбум ₮,"УБ — Хан-Уул, Хан-Уул, Хороо 17",Өнөөдөр
2,https://www.unegui.mn/adv/9304123_2-davkhar-ob...,2 давхар обьект,150 сая ₮,"УБ — Сонгинохайрхан, Сонгинохайрхан, Хороо 35",Өнөөдөр
3,https://www.unegui.mn/adv/9302554_nisekhed-1-o...,Нисэхэд 1 өрөө байр 39мкв,2.8 сая ₮,"УБ — Хан-Уул, Нисэх",Өнөөдөр
4,https://www.unegui.mn/adv/8146458_8-oroo-bair-...,Бгд 256мкв 8 өрөө байр,950 сая ₮,"УБ — Баянгол, Баянгол, Хороо 17",Өнөөдөр

In [132]:
from bs4 import BeautifulSoup
import time

output_lis = []
for ind, url in enumerate(data["url"][:50]):
    print(ind)
    reqs = requests.get(url)
    soup = BeautifulSoup(reqs.content, 'html.parser')
    table = soup.find(class_ = "chars-column")
    table_list = table.find_all("li")
    table_dic = {}
    for table_element in table_list:
        table_key = table_element.find(class_ ="key-chars").text.strip()
        table_value = table_element.find(class_ ="value-chars").text.strip()
        table_dic[table_key]=table_value
    time.sleep(2)
    output_lis.append(table_dic)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [133]:
df_dict = pd.DataFrame.from_dict(output_lis)
df_dict

,Шал:,Тагт:,Ашиглалтанд орсон он:,Гараж:,Цонх:,Барилгын давхар:,Хаалга:,Талбай:,Хэдэн давхарт:,Төлбөрийн нөхцөл:,Цонхны тоо:,Барилгын явц:,Цахилгаан шаттай эсэх:,Төрөл:,Зориулалт:
0,Паркет,1 тагттай,2024,Байхгүй,Вакум,12,Бүргэд,79.42 м²,3,Банкны зээлээр авах боломжтой,3,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
1,Паркет,2 тагттай,2023,Байгаа,Вакум,17,Бүргэд,380.0 м²,16,Банкны зээлээр авах боломжтой,8,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Обьект,NaN
3,Паркет,1 тагттай,2025,Байхгүй,Вакум,11,Бүргэд,39.0 м²,9,Бэлэн төлөлтөөр зарах боломжтой,1,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
4,Паркет,Тагтгүй,2018,Байхгүй,Модон вакум,14,Мод,256.0 м²,13,Банкны зээлээр авах боломжтой,8,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
5,Паркет,1 тагттай,2009,Байгаа,Вакум,6,Бүргэд,89.0 м²,6,Бэлэн төлөлтөөр зарах боломжтой,5,Ашиглалтад орсон,Цахилгаан шатгүй,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180 м² м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад орсон,NaN,"Зуслан, Лагерь",NaN
7,Паркет,2 тагттай,2025,Байгаа,Вакум,3,Бүргэд,81.0 м²,1,Бартераар зарах боломжтой,4,Ашиглалтад орсон,Цахилгаан шатгүй,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад ороогүй,NaN,Агуулах,NaN
9,Паркет,Тагтгүй,2017,Байгаа,Төмөр вакум,16,Төмөр,89.04 м²,7,Банкны зээлээр авах боломжтой,3,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
10,Паркет,1 тагттай,2014,Байгаа,Вакум,6,Бүргэд,176.8 м²,4,Банкны зээлээр авах боломжтой,5,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
11,Паркет,1 тагттай,2008,Байгаа,Вакум,5,Төмөр,206.0 м²,4,Бартераар зарах боломжтой,8,Ашиглалтад орсон,Цахилгаан шатгүй,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бартераар зарах боломжтой,NaN,Ашиглалтад орсон,NaN,В1,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80 м² м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,АОС,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад орсон,NaN,Амралтын газар,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300 м² м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад орсон,NaN,АОС,NaN
16,Паркет,1 тагттай,2009,Байгаа,Вакум,12,Бүргэд,126.0 м²,3,Банкны зээлээр авах боломжтой,5,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
17,Паркет,1 тагттай,2023,Байхгүй,Вакум,10,Бүргэд,173.26 м²,10,Бэлэн төлөлтөөр зарах боломжтой,8,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бартераар зарах боломжтой,NaN,NaN,NaN,NaN,Барилга байгууламжийн зориулалттай
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бартераар зарах боломжтой,NaN,NaN,NaN,NaN,Барилга байгууламжийн зориулалттай
20,Паркет,1 тагттай,2023,Байхгүй,Вакум,7,Бүргэд,40.05 м²,2,Бэлэн төлөлтөөр зарах боломжтой,2,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
21,Паркет,3+ тагттай,2025,Байгаа,Вакум,19,Бүргэд,281.79 м²,10,Банкны зээлээр авах боломжтой,8,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
22,Паркет,1 тагттай,2020,Байхгүй,Вакум,23,Бүргэд,70.0 м²,2,Банкны зээлээр авах боломжтой,3,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,271 м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Хаус,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Обьект,NaN
25,Паркет,1 тагттай,2022,Байхгүй,Вакум,3,Бүргэд,81.21 м²,3,Бэлэн төлөлтөөр зарах боломжтой,5,Ашиглалтад орсон,Цахилгаан шатгүй,NaN,NaN
26,Паркет,Тагтгүй,2024,Байхгүй,Вакум,16,Бүргэд,45.0 м²,11,Бэлэн төлөлтөөр зарах боломжтой,2,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,NaN,NaN,Хашаа байшин,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Нийтийн байр,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,176 м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Хаус,NaN
30,Паркет,1 тагттай,2020,Байгаа,Вакум,6,Төмөр,205.0 м²,5,Бэлэн төлөлтөөр зарах боломжтой,5,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Банкны зээлээр авах боломжтой,NaN,NaN,NaN,NaN,Барилга байгууламжийн зориулалттай
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,NaN,NaN,NaN,Зуслангийн газар
33,Мод,3+ тагттай,2024,Байгаа,Вакум,16,Бүргэд,304.11 м²,12,Банкны зээлээр авах боломжтой,6,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,NaN,NaN,NaN,Барилга байгууламжийн зориулалттай
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47 м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,NaN,NaN
36,Паркет,Тагтгүй,1990,Байхгүй,Вакум,5,Бүргэд,43.5 м²,1,Банкны зээлээр авах боломжтой,3,Ашиглалтад орсон,Цахилгаан шатгүй,NaN,NaN
37,Паркет,1 тагттай,2023,Байхгүй,Вакум,16,Төмөр,37.0 м²,6,Бэлэн төлөлтөөр зарах боломжтой,3,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад ороогүй,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,NaN,NaN,Хашаа байшин,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад орсон,NaN,Лангуу,NaN
41,Паркет,1 тагттай,2022,Байгаа,Вакум,6,Бүргэд,374.0 м²,5,Банкны зээлээр авах боломжтой,7,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,243 м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Хаус,NaN
43,Паркет,1 тагттай,2024,Байхгүй,Вакум,20,Бүргэд,304.0 м²,11,Бартераар зарах боломжтой,5,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20000 м²,NaN,Бэлэн төлөлтөөр зарах боломжтой,NaN,Ашиглалтад орсон,NaN,Хаус,NaN
45,Паркет,1 тагттай,2022,Байхгүй,Вакум,20,Бүргэд,60.1 м²,4,Бэлэн төлөлтөөр зарах боломжтой,3,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,427 м²,NaN,Банкны зээлээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Хаус,NaN
47,Паркет,Тагтгүй,2017,Байгаа,Вакум,12,Төмөр,131.0 м²,11,Банкны зээлээр авах боломжтой,5,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
48,Паркет,1 тагттай,2014,Байхгүй,Вакум,9,Бүргэд,39.47 м²,3,Бэлэн төлөлтөөр зарах боломжтой,1,Ашиглалтад орсон,Цахилгаан шаттай,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Хувь лизингээр авах боломжтой,NaN,Ашиглалтад орсон,NaN,Обьект,NaN

In [134]:
df_dict.to_excel("/Users/ddam-m0101/Downloads/unegui_table.xlsx",index = False)